### ISSUE TITLE
Add unit tests.

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalbazaar/ezcap-express#12]
Add tests to this library. Use https://github.com/digitalbazaar/authorize-access-token-middleware/blob/main/test/main.spec.js as a template (it mounts the middleware on a simple express app, and makes http requests to it).

Feel free to use PR https://github.com/digitalbazaar/did-cli/pull/40 (did-cli/`#delegate` branch) to create mock data zcaps.

In terms of endpoints to test, use a Docs-like model (`/documents/`, `/documents/doc1`, etc).

**Comment by JSAssassin** [comment]
Closing, addressed https://github.com/digitalbazaar/ezcap-express/pull/13 & https://github.com/digitalbazaar/ezcap-express/pull/18
